import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'theme/app_theme.dart';
import 'screens/onboarding_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/home_placeholder_screen.dart';
import 'services/auth_service.dart';

// Generated by running `flutterfire configure` in the project root.
// See README.md for setup instructions.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const FitnessApp());
}

class FitnessApp extends StatelessWidget {
  const FitnessApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FitTrack',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const AuthGate(),
    );
  }
}

/// Decides which screen to show at launch:
/// 1. If a user is already logged in -> Home Dashboard
/// 2. If not logged in but onboarding was already seen -> Login
/// 3. Otherwise (first launch) -> Onboarding
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  Future<bool> _hasSeenOnboarding() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool('onboarding_complete') ?? false;
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService().authStateChanges,
      builder: (context, authSnapshot) {
        if (authSnapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        if (authSnapshot.hasData) {
          return const HomePlaceholderScreen();
        }

        // Not logged in: check whether to show onboarding or login.
        return FutureBuilder<bool>(
          future: _hasSeenOnboarding(),
          builder: (context, onboardSnapshot) {
            if (!onboardSnapshot.hasData) {
              return const Scaffold(
                body: Center(child: CircularProgressIndicator()),
              );
            }
            return onboardSnapshot.data == true
                ? const LoginScreen()
                : const OnboardingScreen();
          },
        );
      },
    );
  }
}
